/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 chair.gltf --transform
Author: Uriel Bromberg (https://sketchfab.com/UrielBromberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-chair-d67bd156478c4b0fac55304ac7b7154f
Title: SCI-FI CHAIR
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3dModel/chair-transformed.glb')
  const { actions } = useAnimations(animations, group)
  // actions.play()
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="lofi_chair" position={[0, 341.902, -139.327]} rotation={[-Math.PI / 2, 0, -0.028]} scale={[109.964, 100, 101.199]}>
            <mesh name="lofi_chair_lofi_chair_base_0" geometry={nodes.lofi_chair_lofi_chair_base_0.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <mesh name="lofi_chair_torus_lofi_chair_corners_0" geometry={nodes.lofi_chair_torus_lofi_chair_corners_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dModel/chair-transformed.glb')
